language: python

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.6'
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - python helloworld.py -p $splunk_pw
on:
    branch: master
